language: java
jdk:
  - oraclejdk8
before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

install:
  - mvn --settings .travis/settings.xml validate -DskipTests=false -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
  - chmod +x .travis/*.sh
  - ls -al .travis
script: mvn help:system
deploy:
  -
    provider: script
    script:
      - .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: solambda/swiffer
      branch: master
      jdk: oraclejdk8
  -
    provider: script
    script:
      - .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: solambda/swiffer
      tags: true
      jdk: oraclejdk8
      
after_success:
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r target/site/jacoco-ut/jacocoTestReport.xml
