package com.solambda.swiffer.api;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

import java.lang.annotation.Documented;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import com.amazonaws.services.simpleworkflow.model.EventType;
import com.amazonaws.services.simpleworkflow.model.StartChildWorkflowExecutionFailedEventAttributes;

/**
 * Handler for the {@link EventType#StartChildWorkflowExecutionFailed} event.
 * <p>
 * The annotated method may have the following parameters:
 * <ul>
 * <li>any parameter that is common to all event handlers
 * <li>the default parameter is {@code cause}: the cause of the failure (information is generated by the system).
 * </ul>
 *
 * @see EventHandlerCommonParameter
 * @see StartChildWorkflowExecutionFailedEventAttributes
 */
@Documented
@Retention(RUNTIME)
@Target(METHOD)
@EventHandler
public @interface OnStartChildWorkflowFailed {

    /**
     * The child {@link WorkflowType} that failed to start.
     *
     * @return the failed workflow type
     */
    Class<?> value();
}
