package com.solambda.aws.swiffer.api.model;

public enum ContextCategory {
	LAMBDA,
	ACTIVITY,
	TIMER,
	CHILD_WORKFLOW,
	MARKER,
	DECISION,
	WORKFLOW_EXECUTION,
	CANCEL_EXTERNAL_WORKFLOW,
	SIGNAL_EXTERNAL_WORKFLOW,
	SIGNAL;
	// CONTINUE_AS_NEW,
}
